### ISSUE TITLE
No Response when over 4g

### ISSUE THREAD

**Issue by alucarddelta** [xNinjasx/homebridge-garadget#2]
There appears to be an issue with the Garadget while over 4g.

While connected to Wifi, Garadget works as expected. So I know that it is configured correctly and working.

![30412541_10157477921494966_2786368490070605824_o](https://user-images.githubusercontent.com/20882097/38464075-aac553ae-3b4a-11e8-84a0-8e03b1b458f6.png)

While connected over 4g, I get a no response message.

![30440842_10157477921384966_7894735032097439744_o](https://user-images.githubusercontent.com/20882097/38464076-bebdd7d2-3b4a-11e8-9647-3bb1a70ce652.png)

All other Homebridge devices (I have 2) are responding as expected. While the other devices take a few seconds to load the status, the garadget responds within 2 seconds as no response. Could this be a timeout issue as it is not waiting long enough?

**Comment by alucarddelta** [comment]
Having this come up as no response also effects the automation.  Any automation I set to the door status (when I am arriving or otherwise) will change the automation profile to disabled as it thinks the device is offline.

The automation issue started about 3 months ago (It didn't really bother me), but the 4g issue I noticed yesterday.

**Comment by alucarddelta** [comment]
The official app works normally over wifi and 4g

**Comment by alucarddelta** [comment]
Checked output from homebridge. It doesn't even show the request over the 4g network.

I have updated to the latest release of both homebridge and the garadget plugin

```
Jun 12 20:35:38 MasterServer2 homebridge[13657]: [12/6/2018, 8:35:38 PM] Homebridge is running on port 51826.
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Getting current state...
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Get ObstructionDetected...
Jun 12 20:36:30 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:30 PM] [Main Garage Door] Getting current state...
Jun 12 20:36:31 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:31 PM] [Main Garage Door] Door state is closed
Jun 12 20:36:31 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:31 PM] [Main Garage Door] Door state is closed
Jun 12 20:36:32 MasterServer2 homebridge[13657]: [12/6/2018, 8:36:32 PM] [Main Garage Door] Access Key good...
```

**Comment by xNinjasx** [comment]
I am really sorry that I just saw this thread. Do you own a Apple TV? An Apple TV is required for remote access to homekit. I understand that you are able to get status on other homekit items but they might be using another protocol to get the status.

**Comment by alucarddelta** [comment]
Yes I do have an Apple TV. I have it configured so remote Homekit is possible. All my other Homekit devices like my Elgato Eves sensors (which require an apple TV for remote access) works fine.

The remote access for Garadget was working normally, till it just stopped randomly.

At first I thought it was they Key to access the device might of timed out. But if that was the case, I would of thought that while on the LAN it would also fail as it wouldn't be able to access the polling site and authenticate.

**Comment by xNinjasx** [comment]
Is this the only homebridge plugin you got? Could be that your router needs to open the port 51826
I don't think my plugin deals with apple homekit at all. we have homebridge inbetween that does all the connection to homekit. you might want to add a simple homebridge plugin such as pi temperture to see if that goes offline too.

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:39",
    "port": 51826,
    "pin": "031-45-154"
  }
```

**Comment by xNinjasx** [comment]
Hope you are doing well. did you get it fixed?

**Comment by alucarddelta** [comment]
Yah it resolved itself over time and I forgot about this issue I raised. Not sure on the root cause or what solved it in the end.

**Comment by xNinjasx** [comment]
Glad to hear. happy to know you are safe and healthy still HA :P
